### ISSUE TITLE
Support channel and README file update

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Reminder#10]
Hi @CasN 

Today someone opened an [issue on MantisBT bugtracker](https://www.mantisbt.org/bugs/view.php?id=32954) regarding your plugin. I moved it to the [specific project](https://www.mantisbt.org/bugs/set_project.php?project_id=7) for this plugin, but earlier this year I added a sticky issue to redirect people here.

I only realized today that *Issues* were not enabled for some reason, so I changed that in the repo's settings. The README file needs to be updated.

I let you take care of that, respond to the user and close the issue.

**Comment by CasN** [comment]
I am on it, the same person also added this to the forum. Will be followed up soonest.

**Comment by CasN** [comment]
Update released and given an update on the forum

**Comment by dregad** [comment]
Thanks 👍 

FYI I fixed a markdown formatting issue in the README.
