### ISSUE TITLE
"Run scheduled script on the account of:" field

### ISSUE THREAD

**Issue by InkVeryOriginal** [mantisbt-plugins/Reminder#11]
Greetings,
I can't understand what account shall I enter in the aforementioned field available via Mantis Configure Plugins page. I also couldn't find description of that field in readme. Could you please elaborate what exactly is supposed to be entered in that field?

**Comment by CasN** [comment]
In principle I would advise to use an account with enough rights, so I suggest something like the admin account (mantis account).
I will update the readme accordingly.
