### ISSUE TITLE
"Database query failed" while trying to launch bug_reminder_mail.php

### ISSUE THREAD

**Issue by InkVeryOriginal** [mantisbt-plugins/Reminder#12]
Greetings,
I'm getting error when I launch bug_reminder_mail.php script via Cron. See exact error message below:

APPLICATION ERROR #401: Database query failed. Error - #1054: Unknown column 'mantis_bug_table.project_id' in 'where clause', query: select bugs.id, bugs.handler_id, bugs.project_id, bugs.priority, bugs.category_id, bugs.status, bugs.severity, bugs.summary from mantis_bug_table bugs JOIN mantis_bug_text_table text ON (bugs.bug_text_id = text.id) where status in (50) and due_date&lt;=1696318201 and handler_id&lt;&gt;0  and due_date&gt;1 and mantis_bug_table.project_id NOT IN (0) order by handler_id.

The column in question, 'mantis_bug_table.project_id', does exist (as far as I understand) if I check it myself via PHPMyAdmin (screnshot attached). 
Could you please assist me on that? Regretfully I'm not at all proficient in database administration, so I'd need instructions if it'll be necessary to do something about database itself. 

My MantisBT version is 2.25.2
My Reminder Plugin version is 2.17
![image](https://github.com/mantisbt-plugins/Reminder/assets/146044218/c1aab67d-4d81-48b4-a50b-982da63d38e3)

**Comment by CasN** [comment]
Think you are using Reminder version 2.17.
This issue is resolved in the latest version (2.20) which you can download here

**Comment by InkVeryOriginal** [comment]
That is the case, I've updated and it works without issues now.
Thanks.
