### ISSUE TITLE
APPLICATION ERROR #401 with Mantis 2.26.1

### ISSUE THREAD

**Issue by pikachurus** [mantisbt-plugins/Reminder#15]
php8.1-fpm / mantisbt 2.26.1

start via cron:
/usr/bin/php /var/www/job/plugins/Reminder/scripts/bug_reminder_mail.php

APPLICATION ERROR #401: Database query failed. Error received from database was - #1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1, query: select bugs.id, bugs.handler_id, bugs.project_id, bugs.priority, bugs.category_id, bugs.status, bugs.severity, bugs.summary from mantis_bug_table bugs JOIN mantis_bug_text_table text ON (bugs.bug_text_id = text.id) where status in (20,21,30,40,50,53,54,55,56,57,60,71) and due_date&lt;=1713986272 and handler_id&lt;&gt;0  and due_date&gt;1 and bugs.project_id NOT IN ().

**Comment by CasN** [comment]
Issue fixed in version 2.21

**Comment by pikachurus** [comment]
updated plugin to 2.21, and error:
#1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1, запрос: select bugs.id, bugs.handler_id, bugs.project_id, bugs.priority, bugs.category_id, bugs.status, bugs.severity, bugs.summary from mantis_bug_table bugs JOIN mantis_bug_text_table text ON (bugs.bug_text_id = text.id) where status in (20,21,30,40,50,53,54,55,56,57,60,71) and due_date&lt;=1714030685 and handler_id&lt;&gt;0  and due_date&gt;1 and bugs.project_id NOT IN ().

**Comment by CasN** [comment]
Ah, I forgot the other side of the eqasion. Should be ok now!

**Comment by pikachurus** [comment]
thank you! all works!
