### ISSUE TITLE
Repeated admin password request deletes all settings

### ISSUE THREAD

**Issue by pattyland** [mantisbt-plugins/Reminder#16]
Hello,
at first I thought it was an exceptional error, but we have now been able to reproduce it reliably:

Case 1:
- Accessing the settings of the reminder plugin as admin
- Changes to settings
- Saving
- Changes were saved

Case 2:
- Accessing the settings from the reminder plugin as admin
- Changes to settings
- Short delay, e.g. because you first have to discuss a setting with others
- Saving
- Prompt to re-enter the admin password due to Mantis admin session timeout

Expected behavior:
- Changes have been saved

Actual behavior:
- All plugin settings are deleted and overwritten with the default settings

Plugin Version: 2.22

Kind regards
Sören

**Comment by CasN** [comment]
Well, I can confirm this is happening. I will make an adjustment in the coming days to the config section in order to ensure this does not happen again.

**Comment by pattyland** [comment]
Updated to 2.23, now we get a `APPLICATION ERROR #2800` after reauthentication timeout and you can go back in the browser, resubmit without problems and nothing is overwritten. Thanks for the quick fix!

**Comment by pattyland** [comment]
Updated to 2.23, now we get a `APPLICATION ERROR #2800` after reauthentication timeout and you can go back in the browser, resubmit without problems and nothing is overwritten. Thanks for the quick fix!
